name: build
on: push
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: '14'
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload Actions Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: build/libs/
    - name: Get Tag Name
      uses: olegtarasov/get-tag@v2
      id: tag_name
    - name: Publish to Bintray
      if: ${{ startsWith(steps.tag_name.outputs.tag, 'v') }}
      run: ./gradlew bintrayUpload
      env:
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
    - name: Create Release
      if: ${{ startsWith(steps.tag_name.outputs.tag, 'v') }}
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_name.outputs.tag }}
        release_name: ${{ steps.tag_name.outputs.tag }}
        prerelease: ${{ contains(github.ref, '-') }}
    - name: Upload Release Asset
      if: ${{ startsWith(steps.tag_name.outputs.tag, 'v') }}
      uses: AButler/upload-release-assets@v2.0
      with:
        files: build/libs/*
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ steps.tag_name.outputs.tag }}
